# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
